### ISSUE TITLE
1.0.0-rc.11 cannot find module - nth-check 

### ISSUE THREAD

**Issue by harlan-zw** [cheeriojs/cheerio#2546]
Came across this exception when upgrading two separate packages to 1.0.0-rc.11.

**Stacktrace:**

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/harlan/packages/unlighthouse/node_modules/.pnpm/nth-check@2.1.0/node_modules/nth-check/lib/esm/parse' imported from /home/harlan/packages/unlighthouse/node_modules/.pnpm/nth-check@2.1.0/node_modules/nth-check/lib/esm/index.js
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:416:11)
    at moduleResolve (node:internal/modules/esm/resolve:932:10)
    at defaultResolve (node:internal/modules/esm/resolve:1044:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

Rolling back the version fixed it.

Not exactly sure what's going on as they both seem to use the same version of nth-check

````
cheerio 1.0.0-rc.11
└─┬ cheerio-select 2.1.0
  └─┬ css-select 5.1.0
    └── nth-check 2.1.0
````

```
cheerio 1.0.0-rc.10
└─┬ cheerio-select 1.6.0
  └─┬ css-select 4.3.0
    └── nth-check 2.1.0
```

**Comment by fb55** [comment]
Thanks for the report — fixed in https://github.com/fb55/nth-check/commit/aeeb0676f6af940e8639f64e27781443694ca05e!
